export type Game = {
  slug: string
  title: string
  description: string
  thumbnail: string
  category: string
  component: string
  featured?: boolean
  plays?: number
  rating?: number
  isNew?: boolean
  isHot?: boolean
}

export type Category = {
  slug: string
  label: string
  icon: string
}

export const categories: Category[] = [
  { slug: 'all', label: 'All Games', icon: '🎮' },
  { slug: 'arcade', label: 'Arcade', icon: '🕹️' },
  { slug: 'puzzle', label: 'Puzzle', icon: '🧩' },
  { slug: 'action', label: 'Action', icon: '⚡' },
  { slug: 'strategy', label: 'Strategy', icon: '🏰' },
  { slug: 'sports', label: 'Sports', icon: '⚽' },
  { slug: 'kids', label: 'Kids', icon: '🧸' },
]

export const games: Game[] = [
  {
    slug: 'snake',
    title: 'Snake',
    description: "Classic snake game. Eat food, grow longer, and don't hit the walls or yourself!",
    thumbnail: '/games/snake/thumb.svg',
    category: 'arcade',
    component: 'Snake',
    featured: true,
    plays: 12400,
    rating: 4.5,
  },
  {
    slug: 'tetris',
    title: 'Tetris',
    description: 'Stack falling blocks to clear lines in this timeless puzzle classic.',
    thumbnail: '/games/tetris/thumb.svg',
    category: 'puzzle',
    component: 'Tetris',
    featured: true,
    plays: 9800,
    rating: 4.8,
  },
  {
    slug: '2048',
    title: '2048',
    description: 'Slide and merge tiles to reach the 2048 tile. Simple to learn, hard to master!',
    thumbnail: '/games/2048/thumb.svg',
    category: 'puzzle',
    component: 'Game2048',
    plays: 7600,
    rating: 4.3,
  },
  {
    slug: 'flappy-bird',
    title: 'Flappy Bird',
    description: 'Tap to fly through the pipes. How far can you go without crashing?',
    thumbnail: '/games/flappy-bird/thumb.svg',
    category: 'arcade',
    component: 'FlappyBird',
    featured: true,
    plays: 21300,
    rating: 4.6,
    isHot: true,
  },
  {
    slug: 'breakout',
    title: 'Breakout',
    description: 'Break all the bricks with your paddle and ball. Clear every level!',
    thumbnail: '/games/breakout/thumb.svg',
    category: 'arcade',
    component: 'Breakout',
    plays: 5200,
    rating: 4.1,
  },
  {
    slug: 'space-invaders',
    title: 'Space Invaders',
    description: 'Blast alien invaders in this retro space shooter. Survive the waves!',
    thumbnail: '/games/space-invaders/thumb.svg',
    category: 'action',
    component: 'SpaceInvaders',
    plays: 8900,
    rating: 4.4,
  },
  {
    slug: 'pac-man',
    title: 'Pac-Man',
    description: 'Navigate the maze, eat all the dots, and avoid the ghosts. Eat power pellets to turn the tables!',
    thumbnail: '/games/pac-man/thumb.svg',
    category: 'arcade',
    component: 'PacMan',
    plays: 18500,
    rating: 4.7,
    isHot: true,
  },
  {
    slug: 'pong',
    title: 'Pong',
    description: 'The original arcade classic. Beat the CPU paddle and be first to 10 points!',
    thumbnail: '/games/pong/thumb.svg',
    category: 'arcade',
    component: 'Pong',
    plays: 6300,
    rating: 4.0,
    isNew: true,
  },
  {
    slug: 'asteroids',
    title: 'Asteroids',
    description: 'Pilot your ship through an asteroid field. Shoot rocks, survive waves, collect points!',
    thumbnail: '/games/asteroids/thumb.svg',
    category: 'action',
    component: 'Asteroids',
    plays: 7100,
    rating: 4.5,
    isNew: true,
  },
  {
    slug: 'minesweeper',
    title: 'Minesweeper',
    description: 'Reveal all safe cells without hitting a mine. Use number clues and flags wisely!',
    thumbnail: '/games/minesweeper/thumb.svg',
    category: 'puzzle',
    component: 'Minesweeper',
    plays: 11200,
    rating: 4.6,
  },
  {
    slug: 'fruit-ninja',
    title: 'Fruit Ninja',
    description: 'Swipe to slice flying fruits before they fall. Miss 3 and the game ends!',
    thumbnail: '/games/fruit-ninja/thumb.svg',
    category: 'arcade',
    component: 'FruitNinja',
    plays: 15700,
    rating: 4.5,
    isHot: true,
  },
  {
    slug: 'doodle-jump',
    title: 'Doodle Jump',
    description: 'Keep jumping higher and higher on platforms. How far can you reach?',
    thumbnail: '/games/doodle-jump/thumb.svg',
    category: 'arcade',
    component: 'DoodleJump',
    plays: 13200,
    rating: 4.4,
    isNew: true,
  },
  {
    slug: 'crossy-road',
    title: 'Crossy Road',
    description: 'Hop across roads, rivers, and train tracks. Time your moves to survive!',
    thumbnail: '/games/crossy-road/thumb.svg',
    category: 'arcade',
    component: 'CrossyRoad',
    plays: 9400,
    rating: 4.3,
    isNew: true,
  },
  {
    slug: 'bubble-shooter',
    title: 'Bubble Shooter',
    description: 'Aim and shoot colored bubbles. Match 3 or more to pop them and clear the board!',
    thumbnail: '/games/bubble-shooter/thumb.svg',
    category: 'puzzle',
    component: 'BubbleShooter',
    plays: 14800,
    rating: 4.5,
    isHot: true,
  },
  {
    slug: 'tower-defense',
    title: 'Tower Defense',
    description: 'Place towers to stop enemy waves from reaching the base. Upgrade and survive!',
    thumbnail: '/games/tower-defense/thumb.svg',
    category: 'strategy',
    component: 'TowerDefense',
    plays: 8600,
    rating: 4.6,
    isNew: true,
  },
  {
    slug: 'memory-match',
    title: 'Memory Match',
    description: 'Flip cards to find matching pairs. Complete the board in the fewest moves!',
    thumbnail: '/games/memory-match/thumb.svg',
    category: 'puzzle',
    component: 'MemoryMatchGame',
    plays: 10100,
    rating: 4.2,
  },
  {
    slug: 'whack-a-mole',
    title: 'Whack-a-Mole',
    description: 'Whack the moles before they disappear! You have 30 seconds — go for the high score!',
    thumbnail: '/games/whack-a-mole/thumb.svg',
    category: 'arcade',
    component: 'WhackAMole',
    plays: 12900,
    rating: 4.3,
    isHot: true,
  },
  {
    slug: 'color-switch',
    title: 'Color Switch',
    description: 'Tap to pass through spinning obstacles — but only through your matching color segment!',
    thumbnail: '/games/color-switch/thumb.svg',
    category: 'action',
    component: 'ColorSwitch',
    plays: 16300,
    rating: 4.7,
    isHot: true,
  },
  {
    slug: 'pool-8',
    title: '8-Ball Pool',
    description: 'Classic 8-ball pool with realistic physics. Play vs CPU or a friend in hot-seat mode. Pot all your balls then sink the 8!',
    thumbnail: '/games/pool-8/thumb.svg',
    category: 'sports',
    component: 'Pool8',
    plays: 89200,
    rating: 4.8,
    isHot: true,
  },
  {
    slug: 'endless-runner',
    title: 'Endless Runner',
    description: 'Run, jump and slide to dodge obstacles! Double-jump over big barriers, slide under low ones. How far can you go?',
    thumbnail: '/thumbnails/endless-runner.svg',
    category: 'arcade',
    component: 'EndlessRunner',
    featured: true,
    plays: 0,
    isHot: true,
  },
  {
    slug: 'simon-says',
    title: 'Simon Says',
    description: 'Watch the colour pattern light up, then repeat it back in order. Each round adds one more step. How far can your memory go?',
    thumbnail: '/thumbnails/simon-says.svg',
    category: 'puzzle',
    component: 'SimonSays',
    plays: 0,
  },
  {
    slug: 'ping-pong',
    title: 'Ping Pong',
    description: 'Classic table tennis vs the CPU! Control your paddle with mouse or keys. First to 7 points wins.',
    thumbnail: '/thumbnails/ping-pong.svg',
    category: 'sports',
    component: 'PingPong',
    plays: 0,
  },
  {
    slug: 'typing-speed',
    title: 'Typing Speed',
    description: "Type the falling words before they hit the ground! Each word scores points. Miss 3 and it's game over. How high can you level?",
    thumbnail: '/thumbnails/typing-speed.svg',
    category: 'puzzle',
    component: 'TypingSpeed',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'brick-breaker',
    title: 'Brick Breaker Deluxe',
    description: 'Break bricks with power-ups: multi-ball, wide paddle, speed boosts! Clear every row to advance. How many levels can you beat?',
    thumbnail: '/thumbnails/brick-breaker.svg',
    category: 'arcade',
    component: 'BrickBreaker',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'gem-blast',
    title: 'Gem Blast',
    description: 'Swap and match colorful gems in this addictive puzzle game. Chain combos, clear the board, and beat your high score!',
    thumbnail: '/games/gem-blast/thumb.svg',
    category: 'puzzle',
    component: 'GemBlast',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'balloon-pop',
    title: 'Balloon Pop',
    description: 'Tap the colorful balloons to pop them before time runs out! Gold balloons are worth extra. A cheerful game for kids.',
    thumbnail: '/games/balloon-pop/thumb.svg',
    category: 'kids',
    component: 'BalloonPop',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'kids-math',
    title: 'Kids Math',
    description: 'Solve fun addition and subtraction sums and pick the right answer. Learn while you play — perfect for young learners!',
    thumbnail: '/games/kids-math/thumb.svg',
    category: 'kids',
    component: 'KidsMath',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'animal-match',
    title: 'Animal Match',
    description: 'Flip the cards and find matching pairs of cute animals. A gentle memory game that little ones will love.',
    thumbnail: '/games/animal-match/thumb.svg',
    category: 'kids',
    component: 'AnimalMatch',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'catch-the-fruit',
    title: 'Catch the Fruit',
    description: 'Move the basket to catch falling fruit and dodge the bombs! Bright, simple and fun for kids of all ages.',
    thumbnail: '/games/catch-the-fruit/thumb.svg',
    category: 'kids',
    component: 'CatchTheFruit',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'piano-tiles',
    title: 'Piano Tiles',
    description: 'Tap the colored tile in each row before it slips off the bottom. Simple, speedy fun that gets faster as you go!',
    thumbnail: '/games/piano-tiles/thumb.svg',
    category: 'arcade',
    component: 'PianoTiles',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'shape-match',
    title: 'Shape Match',
    description: 'Look at the shape at the top and tap the card with the same shape. A gentle shape-recognition game for little ones.',
    thumbnail: '/games/shape-match/thumb.svg',
    category: 'puzzle',
    component: 'ShapeMatch',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'basketball-shoot',
    title: 'Basketball Shoot',
    description: 'Tap to shoot the ball and score when the moving hoop lines up. How many baskets can you sink in 60 seconds?',
    thumbnail: '/games/basketball-shoot/thumb.svg',
    category: 'sports',
    component: 'BasketballShoot',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'lane-runner',
    title: 'Lane Runner',
    description: 'Switch lanes to dodge the cones and run as far as you can in this fast, friendly endless runner. Easy to pick up!',
    thumbnail: '/games/lane-runner/thumb.svg',
    category: 'action',
    component: 'LaneRunner',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'odd-one-out',
    title: 'Odd One Out',
    description: 'One tile has a slightly different colour — can you spot it? The grid grows and the colours get trickier!',
    thumbnail: '/games/odd-one-out/thumb.svg',
    category: 'puzzle',
    component: 'OddOneOut',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'rock-paper-scissors',
    title: 'Rock Paper Scissors',
    description: 'Play the timeless hand game against the computer and build the longest winning streak you can!',
    thumbnail: '/games/rock-paper-scissors/thumb.svg',
    category: 'kids',
    component: 'RockPaperScissors',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'keepy-uppy',
    title: 'Keepy Uppy',
    description: 'Tap the ball to keep it bouncing in the air — do not let it hit the ground! Simple, silly and addictive.',
    thumbnail: '/games/keepy-uppy/thumb.svg',
    category: 'arcade',
    component: 'KeepyUppy',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'number-tap',
    title: 'Number Tap',
    description: 'Tap the numbers in order as fast as you can and beat the clock. A fun way to practise counting!',
    thumbnail: '/games/number-tap/thumb.svg',
    category: 'puzzle',
    component: 'NumberTap',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'quick-math',
    title: 'Quick Math',
    description: 'Is the sum right or wrong? Tap the tick or cross before the timer runs out. A fast-paced mental maths test!',
    thumbnail: '/games/quick-math/thumb.svg',
    category: 'puzzle',
    component: 'QuickMath',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'times-tables',
    title: 'Times Tables',
    description: 'Practise your multiplication tables! Pick the right answer as the tables get bigger. Great for young learners.',
    thumbnail: '/games/times-tables/thumb.svg',
    category: 'kids',
    component: 'TimesTables',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'math-rain',
    title: 'Math Rain',
    description: 'A sum falls from the top — tap its answer before it lands! Quick thinking and quick fingers required.',
    thumbnail: '/games/math-rain/thumb.svg',
    category: 'arcade',
    component: 'MathRain',
    plays: 0,
    isNew: true,
  },
  {
    slug: 'number-bonds',
    title: 'Number Bonds',
    description: 'Tap two numbers that add up to the target. Make as many bonds as you can before time runs out!',
    thumbnail: '/games/number-bonds/thumb.svg',
    category: 'puzzle',
    component: 'NumberBonds',
    plays: 0,
    isNew: true,
  },
]

export function getGame(slug: string): Game | undefined {
  return games.find((g) => g.slug === slug)
}

export function getGamesByCategory(category: string): Game[] {
  if (category === 'all') return games
  return games.filter((g) => g.category === category)
}

export function getFeaturedGames(): Game[] {
  return games.filter((g) => g.featured)
}

export function formatPlays(n: number): string {
  if (n >= 1000) return `${(n / 1000).toFixed(1)}k`
  return String(n)
}
